### PR TITLE
Associations between domain classes

### PR DESCRIPTION
**Pull request by 62Gerente**
Below is a class diagram generated by IntelliJ, where the inheritance relationships are not represented. 

domain_classes_dependencies

New version, with composition over inheritance :fries: 

diagram

### CODE REVIEW

**Comment by pmcleite** [comment]
Este diagrama não permite representar herança, contudo, com o que eu vi estava bem. Apenas não concordo com o relacionamento de 1:1. De resto :+1:

**Comment by 62Gerente** [comment]
The One-To-One relation between RegisteredUser and SystemNotification, was wrong and has already been fixed. Has been changed into a One-to-Many relation as expected.

**Comment by fntneves** [comment]
A mesma notificação não pode pertencer a vários utilizadores, isto é _.._ ?
Btw, o resto parece-me bem. Faltam é elementos do grupo a comentar. :thumbsup:

**Comment by 62Gerente** [comment]
@fntneves 
No, the notification is only the relation between one user and one action. As you can see in the code, it is also in the notification that we have the read boolean.

However, many users can be notified with the same action.

**Pull request closed without merging**
