### PR TITLE
Landing page proposal

### PR DESCRIPTION
**Pull request by fntneves**
Maybe we should change text of last two sections.

**Note**: Unused files will be deleted after group consensus. **Thumbsup must be sent after clean.**

### CODE REVIEW

**Comment by 62Gerente** [comment]
- Change color of header logo (same for footer)
- Change Section 3 text to:
  
  Controla melhor os teus gastos, consultando estatísticas e relatórios das tuas despesas através do painel simples e intuitivo que preparámos para ti.
  
  Vê as tuas ?responsabilidades? organizadas e reduz as tuas preocupações.
  - And add this icons:
  - Stats
  - History
  - Reports
  - Notifications
- Change section 4 topics to:
  - Cria despesas personalizadas para os teus círculos
  - Agenda despesas que recebes regularmente
  - Vê as despesas organizadas por amigo 
  - Desfruta da triangulação de despesas
- Users feedback

**Comment by 62Gerente** [comment]
And do not forget the translations.

**Comment by fntneves** [comment]
Done.
- New logos, black/white with full/single editions;
- Text changed in 3rd and 4th sections;
- Icons added to 3rd section;
- New Users feedback;
- Subscribe responsiveness improved.

To Do:
- Translations

**Comment by 62Gerente** [comment]
:thumbsup: 

To Do:
- Translations
- Images
- Clean HTML and CSS
- Grails integration
- Deploy

**Comment by 62Gerente** [comment]
@fntneves Merge this and close.

**Comment by fntneves** [comment]
@62Gerente I'll merge today.

**Pull request closed without merging**
